export const STORE_IMAGE = 'store_image'
export const FETCH_KITTY = 'fetch_kitty'
export const SAVE_PLAYGROUND = 'save_playground'
export const GET_KITTIES = 'get_kitties'
export const IPFS_HOST = 'http://localhost:8080/ipfs/'
export const STORE_KITTY_IMAGE_DATA = 'store_kitty_image_data'
